### ISSUE TITLE
extract files failed

### ISSUE THREAD

**Issue by zhuang137** [trinket-devs/device_xiaomi_ginkgo#10]
- etc/cne/Nexus/ATT/ATT_profiles.xml
    !! etc/cne/Nexus/ATT/ATT_profiles.xml: file not found in source
  - etc/cne/Nexus/ROW/ROW_profiles.xml
    !! etc/cne/Nexus/ROW/ROW_profiles.xml: file not found in source
  - etc/cne/Nexus/VZW/VZW_profiles.xml
    !! etc/cne/Nexus/VZW/VZW_profiles.xml: file not found in source

where to find these resources????Thanks

**Comment by surfaceflinger** [comment]
You don't need to run extract files. Just use this instead https://github.com/trinket-devs/vendor_xiaomi_ginkgo :)
If you really want to extract files "legal" way then remove `etc/cne/Nexus` lines from proprietary-files.txt

**Comment by zhuang137** [comment]
> You don't need to run extract files. Just use this instead https://github.com/trinket-devs/vendor_xiaomi_ginkgo :)
> If you really want to extract files "legal" way then remove `etc/cne/Nexus` lines from proprietary-files.txt

Thank you very much!  it works for me
