### ISSUE TITLE
Wrong willow/ginkgo detection!

### ISSUE THREAD

**Issue by dimzon** [trinket-devs/device_xiaomi_ginkgo#7]
https://github.com/trinket-devs/device_xiaomi_ginkgo/blob/0a5559ff614b635bb3856e962b2b1e90b2a7bd67/init/init_ginkgo.cpp#L60

Seems like I have a newer HW revision. My phone is willow but is detected as ginkgo... I know other peples with same issues. Please fix it asap!

```
root@nb:/home/me/Downloads/8t_tw/InstalTWRP331-10# adb shell getprop ro.product.device
willow
root@nb:/home/me/Downloads/8t_tw/InstalTWRP331-10# adb shell getprop ro.vendor.build.fingerprint
xiaomi/willow_eea/willow:9/PKQ1.190616.001/V11.0.9.0.PCXEUXM:user/release-keys
root@nb:/home/me/Downloads/8t_tw/InstalTWRP331-10# adb shell getprop ro.boot.hwc
Global_B
root@nb:/home/me/Downloads/8t_tw/InstalTWRP331-10# adb shell getprop ro.boot.hwversion
19.39.0
```

**19**.39.0 not **18**.39.0

**Comment by mg712702** [comment]
Hmm, I need more people to get the hwversion, will look into it

**Comment by dimzon** [comment]
Well at least this guys have same symptoms (they got error in twpr since most used  TWPR from **mauronofrio**  has same issue)
https://forum.xda-developers.com/showpost.php?p=83086035&postcount=63
https://forum.xda-developers.com/showpost.php?p=83106815&postcount=402
https://forum.xda-developers.com/showpost.php?p=83034047&postcount=395

Also at least I guy at russian well-known 4pda forum with same issue confirmed exact same hwversion 
![rn8t](https://user-images.githubusercontent.com/908946/88164208-82925480-cc1c-11ea-8faf-12db2ad1eb90.png)


TWPR issue: https://github.com/mauronofrio/android_device_xiaomi_ginkgo/issues/3

**Comment by adithya2306** [comment]
https://gerrit.aospa.co/c/AOSPA/android_device_xiaomi_ginkgo/+/13301
