### ISSUE TITLE
in BoardConfig.mk ,the clang version 12 ,is it too high ?

### ISSUE THREAD

**Issue by lulml** [trinket-devs/device_xiaomi_ginkgo#9]
in BoardConfig.mk

TARGET_KERNEL_CLANG_VERSION := 12.0
KERNEL_TOOLCHAIN := $(shell pwd)/prebuilts/clang/host/linux-x86/clang-12.0/bin

the clang version 12 ,is it too high ?

**Comment by mg712702** [comment]
Wut?

**Comment by uditkarode** [comment]
Yos too high, should've been 6.9
